# Generated by Django 3.2.20 on 2023-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.IntegerField()),
                ('app', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('request', models.JSONField(null=True)),
                ('response', models.JSONField(null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
